' <auto-generated/>
' This source file is part of the JSON serialization code and is not intended to be modified by you.
' Re-run the source generator will overwrite your changes in this file.
' Generated by: Nukepayload2.IO.Json.Serialization.NewtonsoftJson
Option Strict On
Option Infer On
Option Explicit On
Option Compare Binary
Imports Nukepayload2.AI.Providers.Zhipu.Models
Imports Newtonsoft.Json.Linq

Namespace Serialization
    Partial Class BatchRequestWriter

        ''' <summary>
        ''' Writes <see cref="BatchCreateRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteBatchCreateParams(writer As Global.Newtonsoft.Json.JsonWriter, value As BatchCreateRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.Endpoint IsNot Nothing Then
                writer.WritePropertyName("endpoint")
                writer.WriteValue(value.Endpoint)
            End If
            If value.InputFileId IsNot Nothing Then
                writer.WritePropertyName("input_file_id")
                writer.WriteValue(value.InputFileId)
            End If
            If value.AutoDeleteInputFile IsNot Nothing Then
                writer.WritePropertyName("auto_delete_input_file")
                writer.WriteValue(value.AutoDeleteInputFile)
            End If
            If value.MetadataInternal IsNot Nothing Then
                writer.WritePropertyName("metadata")
                Global.Newtonsoft.Json.JsonSerializer.CreateDefault().Serialize(writer, value.MetadataInternal)
            End If

            writer.WriteEndObject()
        End Sub ' WriteBatchCreateParams

    End Class ' BatchRequestWriter
End Namespace
