' <auto-generated/>
' This source file is part of the JSON serialization code and is not intended to be modified by you.
' Re-run the source generator will overwrite your changes in this file.
' Generated by: Nukepayload2.IO.Json.Serialization.NewtonsoftJson
Option Strict On
Option Infer On
Option Explicit On
Option Compare Binary
Imports Nukepayload2.AI.Providers.Zhipu.Models
Imports Newtonsoft.Json.Linq

Namespace Serialization
    Partial Class FilesRequestWriter

        ''' <summary>
        ''' Writes <see cref="FileUploadRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteFileUploadRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As FileUploadRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.File IsNot Nothing Then
                writer.WritePropertyName("file")
                writer.WriteValue(value.File)
            End If
            If value.Purpose IsNot Nothing Then
                writer.WritePropertyName("purpose")
                writer.WriteValue(value.Purpose)
            End If
            If value.KnowledgeId IsNot Nothing Then
                writer.WritePropertyName("knowledge_id")
                writer.WriteValue(value.KnowledgeId)
            End If

            writer.WriteEndObject()
        End Sub ' WriteFileUploadRequest

        ''' <summary>
        ''' Writes <see cref="FileDeleteRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteFileDeleteRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As FileDeleteRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.FileId IsNot Nothing Then
                writer.WritePropertyName("file_id")
                writer.WriteValue(value.FileId)
            End If

            writer.WriteEndObject()
        End Sub ' WriteFileDeleteRequest

        ''' <summary>
        ''' Writes <see cref="FilesListRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteFilesListRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As FilesListRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.Purpose IsNot Nothing Then
                writer.WritePropertyName("purpose")
                writer.WriteValue(value.Purpose)
            End If
            If value.KnowledgeId IsNot Nothing Then
                writer.WritePropertyName("knowledge_id")
                writer.WriteValue(value.KnowledgeId)
            End If
            If value.Page IsNot Nothing Then
                writer.WritePropertyName("page")
                writer.WriteValue(value.Page)
            End If
            If value.Limit IsNot Nothing Then
                writer.WritePropertyName("limit")
                writer.WriteValue(value.Limit)
            End If
            If value.After IsNot Nothing Then
                writer.WritePropertyName("after")
                writer.WriteValue(value.After)
            End If
            If value.Order IsNot Nothing Then
                writer.WritePropertyName("order")
                writer.WriteValue(value.Order)
            End If

            writer.WriteEndObject()
        End Sub ' WriteFilesListRequest

        ''' <summary>
        ''' Writes <see cref="DocumentRetrieveRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteDocumentRetrieveRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As DocumentRetrieveRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.DocumentId IsNot Nothing Then
                writer.WritePropertyName("document_id")
                writer.WriteValue(value.DocumentId)
            End If

            writer.WriteEndObject()
        End Sub ' WriteDocumentRetrieveRequest

        ''' <summary>
        ''' Writes <see cref="DocumentEditRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteDocumentEditRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As DocumentEditRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.DocumentId IsNot Nothing Then
                writer.WritePropertyName("document_id")
                writer.WriteValue(value.DocumentId)
            End If
            If value.KnowledgeType IsNot Nothing Then
                writer.WritePropertyName("knowledge_type")
                writer.WriteValue(value.KnowledgeType)
            End If
            If value.CustomSeparator IsNot Nothing Then
                writer.WritePropertyName("custom_separator")
                WriteIReadOnlyListOfString(writer, value.CustomSeparator)
            End If
            If value.SentenceSize IsNot Nothing Then
                writer.WritePropertyName("sentence_size")
                writer.WriteValue(value.SentenceSize)
            End If

            writer.WriteEndObject()
        End Sub ' WriteDocumentEditRequest

        ''' <summary>
        ''' Writes array of <see cref="String"/> to JsonWriter.
        ''' </summary>
        Private Shared Sub WriteIReadOnlyListOfString(writer As Global.Newtonsoft.Json.JsonWriter, value As IReadOnlyList(Of String))
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartArray()
            For Each item In value
                writer.WriteValue(item)
            Next
            writer.WriteEndArray()
        End Sub

    End Class ' FilesRequestWriter
End Namespace
