' <auto-generated/>
' This source file is part of the JSON serialization code and is not intended to be modified by you.
' Re-run the source generator will overwrite your changes in this file.
' Generated by: Nukepayload2.IO.Json.Serialization.NewtonsoftJson
Option Strict On
Option Infer On
Option Explicit On
Option Compare Binary
Imports Nukepayload2.AI.Providers.Zhipu.Models
Imports Newtonsoft.Json.Linq

Namespace Serialization
    Partial Class WebSearchRequestWriter

        ''' <summary>
        ''' Writes <see cref="WebSearchRequest"/> to JsonWriter.
        ''' </summary>
        Public Shared Sub WriteWebSearchRequest(writer As Global.Newtonsoft.Json.JsonWriter, value As WebSearchRequest)
            If value Is Nothing Then
                writer.WriteNull()
                Return
            End If

            writer.WriteStartObject()
            If value.SearchEngine IsNot Nothing Then
                writer.WritePropertyName("search_engine")
                writer.WriteValue(value.SearchEngine)
            End If
            If value.SearchQuery IsNot Nothing Then
                writer.WritePropertyName("search_query")
                writer.WriteValue(value.SearchQuery)
            End If
            If value.RequestId IsNot Nothing Then
                writer.WritePropertyName("request_id")
                writer.WriteValue(value.RequestId)
            End If
            If value.UserId IsNot Nothing Then
                writer.WritePropertyName("user_id")
                writer.WriteValue(value.UserId)
            End If

            writer.WriteEndObject()
        End Sub ' WriteWebSearchRequest

    End Class ' WebSearchRequestWriter
End Namespace
